// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _dock200.Data;

namespace _dock200.Migrations
{
    [DbContext(typeof(_DBC))]
    partial class _DBCModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_dock200.Models.RefEmpAp_M", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentlyStudent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateRecieved")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMPCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EMPDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EMPDateTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMPManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighestDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighestLevelAtended")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegallyEligibleEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MayWeContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionAppliedFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SigDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TodayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkEvenings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkWeekends")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("RefEmpAp_M");
                });

            modelBuilder.Entity("_dock200.Models.shinIps2", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IpType")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("seenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stateABR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("timesSeenCount")
                        .HasColumnType("bigint");

                    b.Property<int>("timesSeenDay")
                        .HasColumnType("int");

                    b.Property<long>("totalIpsSeen")
                        .HasColumnType("bigint");

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("shinIps2");
                });

            modelBuilder.Entity("_dock200.Models.shinSiteMetrics", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("pageViewsDebug")
                        .HasColumnType("int");

                    b.Property<int>("pageViewsEx")
                        .HasColumnType("int");

                    b.Property<int>("pageViewsRelease")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("shinSiteMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
